config/routes.rb
Decoo::Application.routes.draw do
  resources :outstock_items

  resources :outstocks do
    
  end

  resources :spec_properties

  resources :specs

  resources :in_stock_items

  resources :in_stocks

  resources :stocks

  resources :colors

  resources :products do
    resources :specs
  end

  get "main/index"
  post "outstocks/find_stock"

  resources :photos









   root :to => 'main#index'


end

app/models/outstock_item.rb
# encoding: utf-8
class OutstockItem < ActiveRecord::Base
  attr_accessible :outstock_id, :product_id, :spec_bh, :spec_id,:weight,:quantity

  belongs_to :outstock
  belongs_to :spec

  validates :spec_bh,:presence => true
  validates :weight,:presence => true,
                    :numericality=>{:greater_than=>0}


#  def spec_bh=(spec_bh_field)
#    self.spec_bh=spec_bh_field
#    if spec=Spec.find_by_bh(spec_bh_field)
#      self.spec_id=spec.id
#      if stock=Stock.find_by_spec_id(spec.id)
#
#      else
#        errors.add(:base,"库存中没有这种规格的零件")
#        return false
#      end
#    else
#      errors.add(:base,"没有这种规格的零件")
#      return false
#    end
#  end

 after_validation :set_item

  def set_item
    if spec=Spec.find_by_bh(self.spec_bh)
      self.spec_id=spec.id
      self.product_id=spec.product_id

      if self.weight && spec.product.weight  && spec.product.weight>0
        if self.weight<spec.product.weight
          errors.add(:weight,"出库重量小于该零件的单位重量")
          return false
        else
          self.quantity=(self.weight/spec.product.weight).round if self.weight
          if stock=Stock.find_by_spec_id(spec.id)
            if stock.quantity<self.quantity
              errors.add(:weight,"库存不足")
              return false
            end
          else
            errors.add(:bh,"库存中没有这种规格的零件")
            return false
          end
        end
        
        
      else
        errors.add(:base,"未输入出库零件重量或者零件未设置单位重量")
        return false
      end
      
      return true
    else
      errors.add(:bh,"没有这种规格的零件")
      return false
    end
  end


end

app/controllers/outstock_items_controller.rb
class OutstockItemsController < ApplicationController
  # GET /outstock_items
  # GET /outstock_items.json
  def index
    @outstock_items = OutstockItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outstock_items }
    end
  end

  # GET /outstock_items/1
  # GET /outstock_items/1.json
  def show
    @outstock_item = OutstockItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outstock_item }
    end
  end

  # GET /outstock_items/new
  # GET /outstock_items/new.json
  def new    
    @outstock_item = OutstockItem.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outstock_item }
      format.js
    end
  end

  # GET /outstock_items/1/edit
  def edit
    @outstock_item = OutstockItem.find(params[:id])
  end

  # POST /outstock_items
  # POST /outstock_items.json
  def create
    @outstock_item = OutstockItem.new(params[:outstock_item])

    respond_to do |format|
      if @outstock_item.valid?() #&& @outstock_item.set_item
        format.html { redirect_to @outstock_item, notice: 'Outstock item was successfully created.' }
        format.json { render json: @outstock_item, status: :created, location: @outstock_item }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @outstock_item.errors, status: :unprocessable_entity }
        format.js   { render ation: "new"}
      end
    end
  end

  # PUT /outstock_items/1
  # PUT /outstock_items/1.json
  def update
    @outstock_item = OutstockItem.find(params[:id])

    respond_to do |format|
      if @outstock_item.update_attributes(params[:outstock_item])
        format.html { redirect_to @outstock_item, notice: 'Outstock item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outstock_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outstock_items/1
  # DELETE /outstock_items/1.json
  def destroy
    @outstock_item = OutstockItem.find(params[:id])
    @outstock_item.destroy

    respond_to do |format|
      format.html { redirect_to outstock_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outstock_items_helper.rb
module OutstockItemsHelper
end

app/views/outstock_items/_form.html.erb
<%= simple_form_for(@outstock_item ,:remote=>true) do |f| %>
  <% if @outstock_item.errors.any? %>
    <div class="alert alert-block alert-error">
      <a class="close" data-dismiss='alert' href="#">×</a>
      <p><strong>有 <%= @outstock_item.errors.count %> 处问题导至无法提交:</strong></p>
      <ul>
        <% @outstock_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="form-inputs">
    <%= f.input :spec_bh %>
    <%#= f.input :spec_id %>
    <%#= f.input :product_id %>
    <%#= f.input :outstock_id %>
    <%= f.input :weight %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/outstock_items/_outstock_item.html.erb
<% if outstock_item.spec  %>
<tr id="<%= outstock_item.spec.bh %>">
  <td>
    <%= outstock_item.spec.bh if outstock_item.spec %>
  </td>
  <td style="background-color: <%= outstock_item.spec.color.value if outstock_item.spec %>"></td>
  <td>
    <%= outstock_item.spec.color.name if outstock_item.spec %>
  </td>
  <td>
    <%= outstock_item.spec.material if outstock_item.spec %>
  </td>
  <td>
    <%= outstock_item.weight %>
  </td>
  <td>
    <%= outstock_item.quantity %>
  </td>
  <td>
    <a href="#" class="icon icomoon-icon-remove" title="删除" onclick="$('#<%= outstock_item.spec.bh %>').remove();$('tr[id=<%= outstock_item.spec.bh %>]').remove();"></a>
  </td>

</tr>
<% end %>

app/views/outstock_items/create.js.erb
<% if @outstock_item && @outstock_item.errors.empty? %>
$('#add-modal').modal('hide');
$('#outstock_items').prepend("<%= escape_javascript(render(@outstock_item) ) %>");
$('#new_outstock').prepend("<div id=\"<%= @outstock_item.spec_bh %>\"> <input type=\"hidden\" name=\"outstock[outstock_items_attributes][][spec_bh]\" value=\"<%= @outstock_item.spec_bh %>\" \/><input type=\"hidden\" name=\"outstock[outstock_items_attributes][][weight]\" value=\"<%= @outstock_item.weight %>\" \/> <\/div>");
<% else %>
  <% flash.now[:error]="有 #{@outstock_item.errors.count} 处问题导至无法提交" %>
$("#add-modal> .modal-body").html("<%= escape_javascript(render(:partial=>'form')) %>");
 $('#add-modal').modal('show');
<% end %>
$('#msg').html("<%= escape_javascript(notice_message ) %>");

app/views/outstock_items/edit.html.erb
<h1>Editing outstock_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @outstock_item %> |
<%= link_to 'Back', outstock_items_path %>

app/views/outstock_items/index.html.erb
<h1>Listing outstock_items</h1>

<table>
  <tr>
    <th>Spec bh</th>
    <th>Spec</th>
    <th>Product</th>
    <th>Outstock</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outstock_items.each do |outstock_item| %>
  <tr>
    <td><%= outstock_item.spec_bh %></td>
    <td><%= outstock_item.spec_id %></td>
    <td><%= outstock_item.product_id %></td>
    <td><%= outstock_item.outstock_id %></td>
    <td><%= link_to 'Show', outstock_item %></td>
    <td><%= link_to 'Edit', edit_outstock_item_path(outstock_item) %></td>
    <td><%= link_to 'Destroy', outstock_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outstock item', new_outstock_item_path %>

app/views/outstock_items/new.html.erb
<h1>New outstock_item</h1>

<%= render 'form' %>

<%= link_to 'Back', outstock_items_path %>

app/views/outstock_items/new.js.erb

$("#add-modal> .modal-body").html("<%= escape_javascript(render(:partial=>'form')) %>");
 $('#add-modal').modal('show');

app/views/outstock_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spec bh:</b>
  <%= @outstock_item.spec_bh %>
</p>

<p>
  <b>Spec:</b>
  <%= @outstock_item.spec_id %>
</p>

<p>
  <b>Product:</b>
  <%= @outstock_item.product_id %>
</p>

<p>
  <b>Outstock:</b>
  <%= @outstock_item.outstock_id %>
</p>


<%= link_to 'Edit', edit_outstock_item_path(@outstock_item) %> |
<%= link_to 'Back', outstock_items_path %>