config/routes.rb
Decoo::Application.routes.draw do
  resources :outstock_items

  resources :outstocks do
    
  end

  resources :spec_properties

  resources :specs

  resources :in_stock_items

  resources :in_stocks

  resources :stocks

  resources :colors

  resources :products do
    resources :specs
  end

  get "main/index"
  post "outstocks/find_stock"

  resources :photos









   root :to => 'main#index'


end

app/models/spec.rb
# encoding: utf-8
class Spec < ActiveRecord::Base
  attr_accessible :bh, :color_id, :product_id, :material,:name,:color_bh,:memo

  validates :color_id,:product_id,:presence=>{:message=>"编号不存在"}
  validates_uniqueness_of :color_id, :scope => :product_id
  
  @@color_exist=true
  belongs_to :product
  belongs_to :color
  has_one :stock
  has_many :in_stock_items,:dependent=>:destroy
  
  
  validate :bh_exist?
  def bh_exist?    
    unless @@color_exist
      errors[:color_id]="没有这种颜色"
    end
  end
  
  #颜色编号验证有问题，需要进一步处理
  def color_bh=(color_bh_field)
    
    color=Color.find_by_bh!(color_bh_field)
    self.color_id=color.id
    @@color_exist=true
  rescue ActiveRecord::RecordNotFound
    @@color_exist=false
    errors[:color_bh]="颜色编号#{color_bh_field}不存在"
    #是否可以用raise 抛出异常 
  end

  def color_bh
    Color.find(self.color_id).bh
  end

  before_save :set_bh
  def set_bh
    self.bh="#{self.product.bh}-#{self.color.bh}"
  end

  after_save :change_stock
  def change_stock
     if self.stock
       self.stock.add_item
       self.stock.save
     end
  end

  before_destroy :check_stock
  def check_stock
    if self.stock
      raise "规格编号为#{self.bh}的零件已加入库存，如要删除请管理员清除此规格零件的库存"
    end
  end


  def material_to_array
    self.material.split(/[\,]/) if self.material
  end


  
end

app/controllers/specs_controller.rb
# encoding: utf-8
class SpecsController < ApplicationController
  # GET /specs
  # GET /specs.json
  def index
    @product=Product.find(params[:product_id])
    @specs = @product.specs.order("id desc")
    @spec=Spec.new(:product_id=>@product.id,:bh=>"#{@product.bh}-")
    respond_to do |format|
      format.html { render :layout=>false }
      format.json { render json: @specs }
      format.js
    end
  end

  # GET /specs/1
  # GET /specs/1.json
  def show
    @spec = Spec.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spec }
    end
  end

  # GET /specs/new
  # GET /specs/new.json
  def new
    @product=Product.find(params[:product_id])
    @spec = Spec.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spec }
      format.js
    end
  end

  # GET /specs/1/edit
  def edit
    @spec = Spec.find(params[:id])
    @materials=SpecProperty.material
    @product=Product.find(params[:product_id])
    
    respond_to do |format|
      format.html {render :layout=>false}
      format.json { render json: @spec }
      format.js  
    end
    
  end

  # POST /specs
  # POST /specs.json
  def create
    @product=Product.find(params[:product_id])    
    params[:spec][:material]=params[:spec][:material].join(",") if params[:spec][:material]
    @spec=@product.specs.build(params[:spec])
    respond_to do |format|

      if @spec.save
        @specs=@spec.product.specs.order('id desc')
        format.html { redirect_to edit_product_url(@product), notice: '新规格已成功创建.' }
        format.json { render json: @spec, status: :created, location: @spec }
        format.js   { render action: "index" }
      else
        format.html { render action: "new" }
        format.json { render json: @spec.errors, status: :unprocessable_entity }
        format.js   { render action: "new"}
      end
    end
  end

  # PUT /specs/1
  # PUT /specs/1.json
  def update
    
    @product=Product.find(params[:product_id])
    @spec = @product.specs.find(params[:id])   
    params[:spec][:material]=params[:spec][:material].join(",") if params[:spec][:material]  
    respond_to do |format|
      if @spec.update_attributes(params[:spec])
        format.html { redirect_to edit_product_url(@product), notice: '新规格已成功修改.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @spec.errors, status: :unprocessable_entity }
        format.js   { render action: "edit" }
      end
    end
  end

  # DELETE /specs/1
  # DELETE /specs/1.json
  def destroy
    @spec = Spec.find(params[:id])
    
    @product=@spec.product
    begin
      @spec.destroy
      @deleted=true
    rescue Exception=>e
      flash.now[:error]=e.message
      @deleted=false
    end
    respond_to do |format|
      format.html { redirect_to edit_product_url(@product), notice: '规格已成功删除.' }
      format.json { head :no_content }
      format.js   {@deleted}
    end

  end
end

app/helpers/specs_helper.rb
module SpecsHelper
end

app/views/specs/_form.html.erb
<% 
    url=@spec.persisted? ?  product_spec_path(@product,@spec) : url=product_specs_path(@product) 

%>

<%= form_for(@spec,:url=> url,:html=>{:class=>'form-horizontal'},:remote=>true) do |f| %>
  <% if @spec.errors.any? %>
    <div class="alert alert-block alert-error">
                <a class="close" data-dismiss='alert' href="#">×</a>
                <p><strong>有 <%= @spec.errors.count %> 处问题导至无法提交:</strong></p>
                <ul>
                  <% @spec.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
  <% end %>

  
  <div class="form-row row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <label for="weight" class="form-label span4">颜色编号</label>
        <input id="spec_color_bh" name="spec[color_bh]" class="span8 focused text" value="<%= @spec.color_bh if @spec.color_id %>"></input>

      </div>
    </div>
  </div>
  <div class="form-row row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <label class="form-label span4" for="checkboxes">材料</label>
        <div class="span8 controls">
          <select name="spec[material][]" class="nostyle" multiple="multiple">
            <%= options_for_select SpecProperty.material,@spec.material_to_array %>
          </select>
        </div>
      </div>
    </div>
  </div>
<div class="form-row row-fluid">
              <div class="span12">
                <div class="row-fluid">
                  <label for="weight" class="form-label span4">备注</label>
                  <%= f.text_area :memo,:class=>'span8 uniform',:rows=>3 %>
                </div>
              </div>
            </div>


  <div class="form-actions">
    <button class="btn btn-info" type="submit" >保存</button>
    <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>

  </div>
<% end %>

app/views/specs/_spec.html.erb
<tr id="spec-<%= spec.id %>" >  
  <td><%= spec.bh %></td>
  <td style="background-color: <%= spec.color.value %>"></td>
  <td><%= spec.color.name %></td>

  <td><%= spec.material %></td>
  <td><%= spec.memo %></td>
  <td>
    <div class="controls center">

      <%= link_to "",edit_product_spec_path(@product,spec),:class=>"icon12 icomoon-icon-pencil",:remote=>true %>
      <%= link_to "", spec, :class => "icon icomoon-icon-remove",'data-confirm' => "确定要删除吗？", :method => :delete, :title => "确定要删除吗？",:remote=>true %>

    </div>
  </td>

</tr>

app/views/specs/create.js.erb


$('#count-spec-<%= @product.id %>').html("<%= @product.specs.size %>");
$('#spec-<%= @product.id %>').html("<%= escape_javascript(render(@specs)) %>");

app/views/specs/destroy.js.erb
<% if @deleted %>
$('#count-spec-<%= @product.id %>').html("<%= @product.specs.size %>");
$('#spec-<%= @spec.id %>').remove();
<% else %>
$('#msg').html("<%=  escape_javascript(notice_message) %> ");
<% end %>

app/views/specs/edit.html.erb
<%= form_for(@spec, :url=>product_spec_path(@product,@spec),:remote=>true,:method=>:put,:html=>{:class=>'form-horizontal'}) do |f| %>
  <% if @spec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spec.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @spec.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-row row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <label for="bh" class="form-label span4">货号</label>
        <%= f.text_field :bh,:class=>'span8 focused text',:readonly=>"readonly" %>
      </div>
    </div>
  </div>
  <div class="form-row row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <label for="weight" class="form-label span4">颜色编号</label>
        <input id="spec_color_bh" name="spec[color_bh]" class="span8 focused text" value="<%= @spec.color_bh %>"></input>
  
      </div>
    </div>
  </div>
  <div class="form-row row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <label class="form-label span4" for="checkboxes">材料</label>
        <div class="span8 controls">
          <select name="spec[material][]" class="nostyle" multiple="multiple">
            <%= options_for_select @materials,@spec.material_to_array %>
          </select>
        </div>
      </div>
    </div>
  </div>
<div class="form-row row-fluid">
              <div class="span12">
                <div class="row-fluid">
                  <label for="weight" class="form-label span4">备注</label>
                  <%= f.text_area :memo,:class=>'span8 uniform',:rows=>3 %>
                </div>
              </div>
            </div>


  <div class="form-actions">
    <button class="btn btn-info" type="submit" onclick="$('#new-spec-modal').modal('hide')">保存</button>
    <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>

  </div>
<% end %>


app/views/specs/edit.js.erb
$("#new-spec-modal> .modal-body").html("<%= escape_javascript(render(:partial=>'form')) %>");

$('#new-spec-modal').modal('show');

app/views/specs/index.html.erb
<div class="contentwrapper"><!--Content wrapper-->
  <div class="heading">

    <h3>零件管理</h3>

    <ul class="breadcrumb">
      <li>You are here:</li>
      <li>
        <a href="#" class="tip" title="back to dashboard">
          <span class="icon16 icomoon-icon-screen"></span>
        </a>
        <span class="divider">
          <span class="icon16 icomoon-icon-arrow-right"></span>
        </span>
      </li>
      <li class="active">零件管理</li>
    </ul>

  </div><!-- End .heading-->
<%= notice_message %>
<div class="row-fluid" >
    <div class="span12">
      <a href="#new-modal" role="button"  class="btn btn-success " data-toggle="modal">
        <span class="icon14 iconic-icon-plus white"></span>
        新增零件
      </a>

      <form class="form-inline pull-right" style="padding-left:20px;" action="<%=  products_path %>">
        <input type="text" class="input-medium search-query" name="search"/>
        <button type="submit" class="btn">搜索</button>
      </form>
    </div>
  </div>

<div class="row-fluid" style="padding: 10px;">
  <div class="span4">
    <img src="/products/<%= @product.image_url %>" class="img-polaroid" style="width:auto;height: 120px;"/>
  </div>
  <div class="span8">
    <p>
      <b>名称:</b>
      <%= @product.title %>
    </p>
    <p>
      <b>编号:</b>
      <%= @product.bh %>
    </p>
    <p>
      <b>重量:</b>
      <%= @product.weight %>
    </p>
    <p>
      <b>备注:</b>
      <%= @product.memo %>
    </p>
  </div>
</div>

<div class="box">
        <div class="title">
          <h4>
            <span class="icon16 brocco-icon-grid"></span>
            <span>规格</span>
          </h4>
        </div>
        <div class="content noPad">
          <div style="padding: 15px;">

            <%= form_for(@spec, :url=>product_specs_path(@product),:remote=>true,:html=>{:class=>'form-horizontal'}) do |f| %>
            <% if @spec.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@spec.errors.count, "error") %> prohibited this product from being saved:</h2>

                <ul>
                  <% @spec.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="row-fluid">
              <div class="span4">
                <div class="form-row row-fluid">
                  <div class="span12">
                    <div class="row-fluid">
                      <label for="bh" class="form-label span4">货号</label>
                      <%= f.text_field :bh,:class=>'span8 focused text',:readonly=>"readonly",:id=>'spec_bh' %>
                    </div>
                  </div>
                </div>
                <div class="form-row row-fluid">
                  <div class="span12">
                    <div class="row-fluid">
                      <label for="weight" class="form-label span4">颜色编号</label>
                      <input id="spec_color_bh" name="spec[color_bh]" class="span8 focused text"></input>
                    </div>
                  </div>
                </div>
              </div>
              <div class="span4">
                <div class="form-row row-fluid">
                  <div class="span12">
                    <div class="row-fluid">
                      <label class="form-label span4" for="checkboxes">材料</label>
                      <div class="span8 controls">
                        <select name="spec[material][]" class="nostyle" multiple="multiple">
                          <%= options_for_select SpecProperty.material %>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="span4">
                <div class="form-row row-fluid">
                  <div class="span12">
                    <div class="row-fluid">
                      <label for="weight" class="form-label span4">备注</label>
                      <%= f.text_area :memo,:class=>'span8 uniform',:rows=>3 %>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="form-actions">
              <button class="btn btn-info" type="submit">
                <span class="icon14 iconic-icon-plus white"></span>
              新增规格
                </button>
            </div>
          <% end %>
          </div>
          <table id="DataTables_Table_0" class="responsive table table-bordered ">
            <thead>
              <tr>
                <th>#</th>
                <th>货号</th>
                <th colspan="2">颜色</th>
                <th>材料</th>
                <th>备注</th>
<%#*<th class="ch" id="masterCh"><div class="checker" id="uniform-undefined"><span><input type="checkbox" class="styled" value="all" name="checkbox" style="opacity: 0;"></span></div></th>%>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody id="specs">

              <%= render(@specs) %>

            <tbody>

            </tbody>
          </table>
          <div style="padding: 10px;">

          </div>
        </div>

      </div><!-- End .box -->

</div>

<div id="new-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">新增零件</h3>
    </div>
    <div class="modal-body">
      <%= form_for(@product, :html=>{:class=>'form-horizontal',:multipart=>true}) do |f| %>
        <% if @product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
              <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-row row-fluid">
          <div class="span12">
            <div class="row-fluid">
              <label for="title" class="form-label span4">名称</label>
              <%= f.text_field :title,:class=>'span8 focused text' %>
            </div>
          </div>
        </div>
        <div class="form-row row-fluid">
          <div class="span12">
            <div class="row-fluid">
              <label for="bh" class="form-label span4">编号</label>
              <%= f.text_field :bh,:class=>'span8 focused text' %>
            </div>
          </div>
        </div>
        <div class="form-row row-fluid">
          <div class="span12">
            <div class="row-fluid">
              <label for="weight" class="form-label span4">重量</label>
              <%= f.text_field :weight,:class=>'span8 focused text' %>
            </div>
          </div>
        </div>
        <div class="form-row row-fluid">
          <div class="span12">
            <div class="row-fluid">
              <label for="weight" class="form-label span4">备注</label>
              <%= f.text_area :memo,:class=>'span8 uniform',:rows=>3 %>
            </div>
          </div>
        </div>
        <div class="form-row row-fluid">
          <div class="span12">
            <div class="row-fluid">
              <label class="form-label span4">上传文件：</label>
              <input type="file" name="product[upload_picture]" class='span8 focused text'></input>
            </div>
          </div>
        </div>


      </div>
      <div class="modal-footer">
        <button class="btn btn-info" type="submit">保存</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>

      </div>
    <% end %>
  </div>

<div id="edit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">修改规格</h3>
    </div>
  <div class="modal-body">

  </div>
</div>

<script type="text/javascript">
  $('body').on('hidden', '.modal', function () {
    $(this).removeData('modal');
  });
  $('#spec_color_bh').change(function(){
    $('#spec_bh').attr("value","<%= @spec.bh %>"+$(this).attr("value"));

  });
</script>

app/views/specs/index.js.erb
$('#new-spec-modal').modal('hide');
$('#count-spec-<%= @product.id %>').html("<%= @product.specs.size %>");
$('#spec-<%= @product.id %>').html(" <table class=\"responsive table table-bordered \"> <thead><tr><th>货号</th>    <th colspan=\"2\">颜色<\/th>                <th>材料<\/th>                <th>备注<\/th>                <th>Actions<\/th>              <\/tr>            <\/thead>            <tbody id=\"specs\"><%= escape_javascript(render(@specs)) %>            <\/tbody><\/table>              ");
$('#spec-<%= @product.id %>').show();
$('#hide-specs-<%= @product.id %>').show();
$('#show-specs-<%= @product.id %>').hide();

app/views/specs/new.html.erb
<h1>New spec</h1>

<%= render 'form' %>

<%= link_to 'Back', specs_path %>

app/views/specs/new.js.erb
# encoding: utf-8
$('#new-spec-modal>.modal-body').html("<%= escape_javascript(render(:partial=>'form')) %>");
$('#new-spec-modal').modal('show');

app/views/specs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bh:</b>
  <%= @spec.bh %>
</p>

<p>
  <b>Name:</b>
  <%= @spec.name %>
</p>

<p>
  <b>Value:</b>
  <%= @spec.value %>
</p>

<p>
  <b>Is color:</b>
  <%= @spec.is_color %>
</p>

<p>
  <b>Color:</b>
  <%= @spec.color_id %>
</p>


<%= link_to 'Edit', edit_spec_path(@spec) %> |
<%= link_to 'Back', specs_path %>

app/views/specs/update.js.erb
$('#new-spec-modal').modal('hide');
$('#spec-<%= @spec.id %>').replaceWith("<%= escape_javascript(render(@spec)) %>");