config/routes.rb
Decoo::Application.routes.draw do
  resources :outstock_items

  resources :outstocks do
    
  end

  resources :spec_properties

  resources :specs

  resources :in_stock_items

  resources :in_stocks

  resources :stocks

  resources :colors

  resources :products do
    resources :specs
  end

  get "main/index"
  post "outstocks/find_stock"

  resources :photos









   root :to => 'main#index'


end

app/models/in_stock.rb
class InStock < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :in_stock_items
end

app/controllers/in_stocks_controller.rb
class InStocksController < ApplicationController
  # GET /in_stocks
  # GET /in_stocks.json
  def index
    @in_stocks = InStock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @in_stocks }
    end
  end

  # GET /in_stocks/1
  # GET /in_stocks/1.json
  def show
    @in_stock = InStock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @in_stock }
    end
  end

  # GET /in_stocks/new
  # GET /in_stocks/new.json
  def new
    @in_stock = InStock.create
    @items=@in_stock.in_stock_items

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @in_stock }
    end
  end

  # GET /in_stocks/1/edit
  def edit
    @in_stock = InStock.find(params[:id])
  end

  # POST /in_stocks
  # POST /in_stocks.json
  def create
    @in_stock = InStock.new(params[:in_stock])

    respond_to do |format|
      if @in_stock.save
        format.html { redirect_to @in_stock, notice: 'In stock was successfully created.' }
        format.json { render json: @in_stock, status: :created, location: @in_stock }
      else
        format.html { render action: "new" }
        format.json { render json: @in_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /in_stocks/1
  # PUT /in_stocks/1.json
  def update
    @in_stock = InStock.find(params[:id])

    respond_to do |format|
      if @in_stock.update_attributes(params[:in_stock])
        format.html { redirect_to @in_stock, notice: 'In stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @in_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /in_stocks/1
  # DELETE /in_stocks/1.json
  def destroy
    @in_stock = InStock.find(params[:id])
    @in_stock.destroy

    respond_to do |format|
      format.html { redirect_to in_stocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/in_stocks_helper.rb
module InStocksHelper
end

app/views/in_stocks/_form.html.erb
<%= form_for(@in_stock) do |f| %>
  <% if @in_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@in_stock.errors.count, "error") %> prohibited this in_stock from being saved:</h2>

      <ul>
      <% @in_stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/in_stocks/edit.html.erb
<h1>Editing in_stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @in_stock %> |
<%= link_to 'Back', in_stocks_path %>

app/views/in_stocks/index.html.erb
<h1>Listing in_stocks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @in_stocks.each do |in_stock| %>
  <tr>
    <td><%= link_to 'Show', in_stock %></td>
    <td><%= link_to 'Edit', edit_in_stock_path(in_stock) %></td>
    <td><%= link_to 'Destroy', in_stock, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New In stock', new_in_stock_path %>

app/views/in_stocks/new.html.erb
<div class="contentwrapper"><!--Content wrapper-->
  <div class="heading">

    <h3>入库管理</h3>

    

    <ul class="breadcrumb">
      <li>You are here:</li>
      <li>
        <a href="#" class="tip" title="back to dashboard">
          <span class="icon16 icomoon-icon-screen"></span>
        </a>
        <span class="divider">
          <span class="icon16 icomoon-icon-arrow-right"></span>
        </span>
      </li>
      <li class="active">入库单</li>
    </ul>

  </div><!-- End .heading-->

  <div class="row-fluid">
    <div class="span12">
      <%= notice_message %>
    </div>
  </div>


  <div class="row-fluid">
    <div class="span12">
      <div class="box">
        <div class="title">
          <h4>
            <span class="icon16 brocco-icon-grid"></span>
            <span>明细</span>
            
<%#*<form action="" class="box-form right">%>
<%#*<a href="#" data-toggle="dropdown" class="btn dropdown-toggle">%>
<%#*<span class="icon16 iconic-icon-cog"></span>%>
<%#*<span class="caret"></span>%>
<%#*</a>%>
<%#*<ul class="dropdown-menu">%>
<%#*<li><a href="#"><span class="icon-plus"></span> 增加</a></li>%>
<%#*<li><a href="#"><span class="icon-trash"></span> 删除</a></li>%>
<%#*</ul>%>
<%#*</form>%>

          </h4>
          <a class="minimize" href="#" style="display: none;">Minimize</a>
        </div>
        <div class="content noPad">
          <div style="padding: 15px;">
            <a href="#new-modal" role="button"  class="btn btn-success " data-toggle="modal">
              <span class="icon14 iconic-icon-plus white"></span>
              新增
            </a>

            <%#*<form class="form-inline pull-right" style="padding-left:20px;">%>
              <%#*<input type="text" class="input-medium search-query">%>
              <%#*<button type="submit" class="btn">搜索</button>%>
            <%#*</form>%>

          </div>
          <table id="checkAll" class="responsive table table-bordered">
            <thead>
              <tr>
                <th>#</th>
                <th colspan="2" >颜色</th>
                <th>编号</th>
                <th>名称</th>
                <th>颜色</th>
                <th>重量</th>
                <th>数量</th>
                
<%#*<th class="ch" id="masterCh"><div class="checker" id="uniform-undefined"><span><input type="checkbox" class="styled" value="all" name="checkbox" style="opacity: 0;"></span></div></th>%>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>


              <% @items.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%= item.name %></td>
                  <td style="background-color: <%= item.color.value %>">

                  </td>
                  <td>
                     <%= item.weight %>
                  </td>
                  <td><%= item.quantity %></td>
                  


  <%#*<td class="chChildren">%>
  <%#*<div class="checker" id="uniform-undefined">%>
  <%#*<span><input type="checkbox" class="styled" value="" name="checkbox" style="opacity: 0;"></span>%>
  <%#*</div>%>
  <%#*</td>%>
                  <td>
                    <div class="controls center">
                      <a class="tip" href="<%= edit_in_stock_item_path(item) %>" oldtitle="Edit task" title="">
                        <span class="icon12 icomoon-icon-pencil"></span>
                      </a>
                      <%= link_to "", item, :class => "icon icomoon-icon-remove",'data-confirm' => "确定要删除吗？", :method => :delete, :title => "确定要删除吗？" %>

                    </div>
                  </td>

                </tr>
              <% end %>
            </tbody>
          </table>

          <div style="padding: 10px;">
            <%#= will_paginate @colors, :inner_window => 2 %>
          </div>

        </div>

      </div><!-- End .box -->

    </div>

  </div>
</div>

<div id="new-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">新增</h3>
  </div>
  <div class="modal-body">
    <%= form_for(@item, :html=>{:class=>'form-horizontal'}) do |f| %>
      <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-row row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <label for="title" class="form-label span4">名称</label>
            <%= f.text_field :name,:class=>'span8 focused text' %>
          </div>
        </div>
      </div>
      
      
      </div>
      


    </div>
    <div class="modal-footer">
      <button class="btn btn-info" type="submit">保存</button>
      <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>

    </div>
  <% end %>
</div>

app/views/in_stocks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_in_stock_path(@in_stock) %> |
<%= link_to 'Back', in_stocks_path %>