config/routes.rb
Decoo::Application.routes.draw do
  resources :outstock_items

  resources :outstocks do
    
  end

  resources :spec_properties

  resources :specs

  resources :in_stock_items

  resources :in_stocks

  resources :stocks

  resources :colors

  resources :products do
    resources :specs
  end

  get "main/index"
  post "outstocks/find_stock"

  resources :photos









   root :to => 'main#index'


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :bh, :color_id, :image_url, :title, :weight,:upload_picture,:memo

  has_many :specs ,:dependent=>:destroy


  validates :bh,:presence => true, :uniqueness => true
  validates :weight,:numericality=>{:greater_than=>0}, :allow_blank => true
  

  @@storage_path =  "#{Rails.root}/public/products"

  def upload_picture=(picture_field)
    self.image_url=uploadFile(picture_field)
  end

  after_save :change_spec
  def change_spec    
    self.specs.each do |spec|
       spec.save!
    end
  end

  protected

  def uploadFile(file)
    if !file.original_filename.empty?
      @filename=getFileName(file.original_filename)
      File.open("#{Rails.root}/public/products/#{@filename}", "wb") do |f|
      f.write(file.read)
      end
      return @filename
    end
  end

  def getFileName(filename)
    timestamp = DateTime.now.strftime("%y%m%d%H%M%S")
    ascii = ''
    if filename =~ %r{^[a-zA-Z0-9_\.\-]*$}
      ascii = filename
    else
      ascii = Digest::MD5.hexdigest(filename)
      # keep the extension if any
      ascii << $1 if filename =~ %r{(\.[a-zA-Z0-9]+)$}
    end
    while File.exist?(File.join(@@storage_path, "#{timestamp}_#{ascii}"))
      timestamp.succ!
    end
    "#{timestamp}_#{ascii}"
  end
  
end

app/controllers/products_controller.rb
# encoding: utf-8
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    
    @product = Product.new
    w="1=1"
    o="bh"
    @search=params[:search]
    @order=params[:order]
    if params[:search] and !params[:search].empty?
      w="title like ? or bh like ? ","%#{params[:search]}%","%#{params[:search]}%"
    end
    if params[:order] and !params[:order].empty?
      o="#{params[:order]}"
    end
    @products = Product.paginate(:page => params[:page], :per_page => 10).where(w).order(o)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    
    respond_to do |format|
      format.html { render :layout=>false } # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
      format.js
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @specs=@product.specs.order('id desc')
    @spec=Spec.new(:product_id=>@product.id,:bh=>"#{@product.bh}-")
    @materials=SpecProperty.material
    respond_to do |format|
      format.html { render :layout=>false }
      format.js
    end
    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_specs_url(@product), notice: '零件已成功创建.' }
        format.json { render json: @product, status: :created, location: @product }
        format.js

      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js   { render action: "new"}
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    @specs=@product.specs
    @spec=Spec.new(:product_id=>@product.id,:bh=>"#{@product.bh}-")
    @materials=SpecProperty.material
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
        format.js   { @current_product=@product }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.js   { render action: "edit"}
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    begin
    @product.destroy
    @deleted=true
    rescue Exception=>e
      flash.now[:error]=e.message
      @deleted=false
    end
    respond_to do |format|
      format.html { redirect_to products_url, notice: '数据已删除.' }
      format.json { head :no_content }
      format.js   { @deleted }
    end
  end

 
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product, :remote=>true,:html=>{:class=>'form-horizontal',:multipart=>true}) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-block alert-error">
      <a class="close" data-dismiss='alert' href="#">×</a>
      <p><strong>有 <%= @product.errors.count %> 处问题导至无法提交:</strong></p>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <div class="row-fluid">
           <%= f.input :title %>
           <%= f.input :bh %>
           <%= f.input :weight %>

      <div class="form-row row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <label for="weight" class="form-label span4">备注</label>
            <%= f.text_area :memo,:class=>'span8 uniform',:rows=>3 %>
          </div>
        </div>
      </div>

      <div class="form-row row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <label class="form-label span4">上传文件：</label>
            <%= f.hidden_field :image_url,:id=>"image-url" %>
           
             <img src="<%= "/products/#{@product.image_url}" if @product.image_url %>" class="img-polaroid" style="width:auto;height: 60px;" id="product-image"/>

              <%= link_to("点击上传", "#", :id => "topic_add_image", :rel => "twipsy", :class => "btn eco-images ")%>

          </div>
        </div>
      </div>

  </div>

  <div class="form-actions">
    <button class="btn btn-info" type="submit" >保存</button>    
<button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
  </div>
<% end %>
<%= controller_javascript_include_tag %>

<div style="display:none;">
    <form >
      <input type="file" id="topic_upload_images"/>
    </form>
</div>

app/views/products/_product.html.erb
<tr id="product_<%= product.id %>">
  <td><%= product.id %></td>
  <td>
    <a title="<%= product.title %>" rel="prettyPhoto" href="/products/<%= product.image_url %>">
      <img src="/products/<%= product.image_url %>" class="img-polaroid" style="width:auto;height: 60px;"/>
    </a>
  </td>
  <td><%= product.bh %></td>
  <td><%= product.title %></td>

  <td><%= product.weight.to_f if product.weight %></td>
  <td>
    <span id="count-spec-<%= product.id %>">
      <%= product.specs.size %>
    </span>
    <span id="show-specs-<%= product.id %>">
      <%= link_to '展开',product_specs_path(product),:class=>"icomoon-icon-arrow-down",:remote=>true %>
    </span>
    <span id="hide-specs-<%= product.id %>" style="display: none;">
      <a href="#" class="icomoon-icon-arrow-up" onclick="$('#spec-<%= product.id %>').hide();$('#hide-specs-<%= product.id %>').hide();$('#show-specs-<%= product.id %>').show();return;">收缩</a>
    </span>
    <%= link_to '增加',new_product_spec_path(product),:class=>"icomoon-icon-plus-2",:remote=>true %>
    <div id="spec-<%= product.id %>" style="display: none;"></div>
  </td>
  <td>
    <%= product.created_at.to_s(:db) %>
  </td>
  <td>
    <div class="controls center">
      <a data-toggle="modal" href="#detail_modal" data-target="#detail_modal" data-remote="<%= product_url(product) %>" class="icon brocco-icon-eye" title="查看产品详细信息"></a>
      <%= link_to '',edit_product_url(product),:class=>"icon icomoon-icon-pencil",:title=>"编辑零件详细信息",:remote=>true %>
      
      <%= link_to "", product, :class => "icon icomoon-icon-remove",'data-confirm' => "同时会删除包含的规格，确定要删除吗？", :method => :delete, :title => "确定要删除吗？",:remote=>true %>

    </div>
  </td>

</tr>

app/views/products/create.js.erb
# encoding: utf-8
$('#product-modal').modal('hide');
$('#products').prepend("<%= escape_javascript(render(@product)) %>");
<% flash.now[:notice]="零件已成功创建" %>
$('#msg').html("<%=  escape_javascript(notice_message) %> ");
$('#product_<%= @product.id %>').fadeOut(1000).fadeIn(1000);

app/views/products/destroy.js.erb
<% if @deleted %>
<% flash.now[:notice]="零件已删除" %>
$('#msg').html("<%=  escape_javascript(notice_message) %> ");
$('#product_<%= @product.id %>').fadeOut(1000);
<% else %>

$('#msg').html("<%=  escape_javascript(notice_message) %> ");
<% end %>

app/views/products/edit.html.erb

<%= simple_form_for(@product, :remote=>true,:html=>{:class=>'form-horizontal',:multipart=>true}) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-block alert-error">
      <a class="close" data-dismiss='alert' href="#">×</a>
      <p><strong>有 <%= @product.errors.count %> 处问题导至无法提交:</strong></p>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <div class="row-fluid">       
           <%= f.input :title %>
           <%= f.input :bh %>
           <%= f.input :weight %>




      <div class="form-row row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <label for="weight" class="form-label span4">备注</label>
            <%= f.text_area :memo,:class=>'span8 uniform',:rows=>3 %>
          </div>
        </div>
      </div>

      <div class="form-row row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <label class="form-label span4">上传文件：</label>
            
            <input type="hidden" name="product[image_url]" id="image-url" />

              <img src="<%= "/products/#{@product.image_url}" if @product.image_url %>" class="img-polaroid" style="width:auto;height: 60px;" id="product-image"/>

              <%= link_to("点击上传", "#", :id => "topic_add_image", :rel => "twipsy", :class => "btn eco-images ")%>
          </div>
        </div>
      </div>
    
  </div>

  <div class="form-actions">
    <button class="btn btn-info" type="submit" onclick="$('#edit_modal').modal('hide')">保存</button>
    <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>

  </div>
<% end %>

<div style="display:none;">
    <form >
      <input type="file" id="topic_upload_images"/>
    </form>
</div>

app/views/products/edit.js.erb
$("#edit_modal> .modal-body").html("<%= escape_javascript(render(:partial=>'form')) %>");


$('#edit_modal').modal('show');

app/views/products/index.html.erb
# encoding: utf-8
<div class="contentwrapper"><!--Content wrapper-->
  <div class="heading">

    <h3>零件管理</h3>

    <ul class="breadcrumb">
      <li>You are here:</li>
      <li>
        <a href="#" class="tip" title="back to dashboard">
          <span class="icon16 icomoon-icon-screen"></span>
        </a>
        <span class="divider">
          <span class="icon16 icomoon-icon-arrow-right"></span>
        </span>
      </li>
      <li class="active">零件管理</li>
    </ul>

  </div><!-- End .heading-->

  <div class="row-fluid">
    <div class="span12" id="msg">
      <%= notice_message %>
    </div>
  </div> 

  <div class="row-fluid">
    <div class="span12">
      <div class="box">
        <div class="title">
          <h4>
            <span class="icon16 brocco-icon-grid"></span>
            <span>零件列表</span>

          </h4>
          <a class="minimize" href="#" style="display: none;">Minimize</a>
        </div>
        <div class="content noPad">
          <div style="padding: 15px;">
            <a href="<%= new_product_path %>"  class="btn btn-success " data-remote="true" >
              <span class="icon14 iconic-icon-plus white"></span>
              新增零件
            </a>
            
            <form class="form-inline pull-right" style="padding-left:20px;" action="<%=  products_path %>">
              <input type="text" class="input-medium search-query" name="search"/>
              <button type="submit" class="btn">搜索</button>
            </form>

          </div>
          <table id="DataTables_Table_0" class="responsive table table-bordered ">
            <thead>
              <tr>
                <th>#</th>
                <th>图片</th>
                <th >编号
                  <a href="<%= products_path %>/?order=bh&search=<%= @search %>" class="icon-arrow-up">
                  </a>
                  <a href='<%= "#{products_path}/?order=bh desc&search=#{@search}" %>' class="icon-arrow-down">
                  </a>
                </th>
                <th>名称</th>
                <th>重量</th>
                <th>规格</th>
                <th>时间
                  <a href="<%= products_path %>/?order=created_at&search=<%= @search %>" class="icon-arrow-up">
                  </a>
                  <a href='<%= "#{products_path}/?order=created_at desc&search=#{@search}" %>' class="icon-arrow-down">
                  </a>
                </th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody id="products">
              <%= render(@products) %>

            </tbody>
          </table>

          <div class="row-fluid" style="padding: 10px;">
            <div class="span3">
              <%= page_entries_info @products %>
            </div>
            <div  class="span9">
              <form class="form-inline pull-left" style="padding-right: 10px;" action="<%= "#{products_path}" %>" >
                <input type="text" class="input-mini" name="page"  />页

                <input type="hidden" name="order" value="<%= @order %>"></input>
                <input type="hidden" name="search" value="<%= @search %>"></input>
                <button type="submit" class="btn">跳转</button>
              </form>
              <%= will_paginate @products, :inner_window => 2,:params=>{:search=>@search,:order=>@order} %>
            </div>
                        
          </div>
          
          
        </div>

      </div><!-- End .box -->

    </div>

  </div>
</div>


<div id="detail_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">零件详细信息</h3>
  </div>
  <div class="modal-body">

  </div>

  <div class="modal-footer">

    <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>

  </div>
</div>
<div id="product-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">零件信息编辑</h3>
  </div>
  <div class="modal-body">

  </div>

</div>

<div id="new-spec-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">编辑规格</h3>
  </div>
  <div class="modal-body">

  </div>

</div>
<script type="text/javascript">
  $('body').on('hidden', '.modal', function () {
    $(this).removeData('modal');
  });
</script>

app/views/products/new.html.erb


<div class="contentwrapper"><!--Content wrapper-->
  <div class="heading">

    <h3>零件管理</h3>
    <ul class="breadcrumb">
      <li>You are here:</li>
      <li>
        <a href="#" class="tip" title="back to dashboard">
          <span class="icon16 icomoon-icon-screen"></span>
        </a>
        <span class="divider">
          <span class="icon16 icomoon-icon-arrow-right"></span>
        </span>
      </li>
      <li class="active">零件管理</li>
    </ul>

  </div><!-- End .heading-->

  <div class="row-fluid">
    <div class="span12">
    <a href="#new-modal" role="button"  class="btn btn-success " data-toggle="modal">
                <span class="icon14 iconic-icon-plus white"></span>
                新增零件
              </a>

              <form class="form-inline pull-right" style="padding-left:20px;" action="<%=  products_path %>">
                <input type="text" class="input-medium search-query" name="search"/>
                <button type="submit" class="btn">搜索</button>
              </form>
      </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <%= notice_message %>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="span12">
      <div class="box">
        <div class="title">
          <h4>
            <span class="icon16 brocco-icon-grid"></span>
            <span>新增</span>
          </h4>
        </div>


        <div class="content ">
          <%= simple_form_for(@product, :html=>{:class=>'form-horizontal',:multipart=>true}) do |f| %>
            <% if @product.errors.any? %>
              <div class="alert alert-block alert-error">
                <a class="close" data-dismiss='alert' href="#">×</a>
                <p><strong>有 <%= @product.errors.count %> 处问题导至无法提交:</strong></p>
                <ul>
                  <% @product.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>

            <% end %>
            <%= f.input :title %>
            <%= f.input :bh %>
            <%= f.input :weight %>
            <%= f.input :memo, input_html: { :rows=>3 } %>
            <div class="control-group file optional">
              <label class="file optional control-label" for="product_memo">上传文件：</label>
              <div class="controls">
                <input type="file" name="product[upload_picture]" class='file optional uniform'></input>
                <% if @product.image_url %>
                    <img src="/products/<%= @product.image_url %>" class="span4 img-polaroid " style="width:69px;height: 60px;" />
                  <% end %>
              </div></div>
            



            <div class="form-actions">
              <button class="btn btn-info" type="submit">保存</button>
              <a class="btn" href="<%= products_path %>">取消</a>

            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


app/views/products/new.js.erb
$("#product-modal> .modal-body").html("<%= escape_javascript(render(:partial=>'form')) %>");
 $('#product-modal').modal('show');   

app/views/products/show.html.erb

<p id="notice"><%= notice %></p>
<div class="row-fluid">
  <div class="span6">
    <img src="/products/<%= @product.image_url %>" class="img-polaroid" style="width:auto;height: 120px;"/>
  </div>
  <div class="span6">
    <p>
      <b>名称:</b>
      <%= @product.title %>
    </p>
    <p>
      <b>编号:</b>
      <%= @product.bh %>
    </p>
    <p>
      <b>重量:</b>
      <%= @product.weight %>
    </p>
    <p>
      <b>备注:</b>
      <%= @product.memo %>
    </p>
  </div>
</div>
<div style="padding: 10px;">
  <p>规格列表
    
  </p>
  <table id="checkAll" class="responsive table table-bordered">
    <thead>
      <tr>
        <th>#</th>        
        <th>货号</th>
        <th>名称</th>
        <th colspan="2" >颜色</th>
        <th>规格</th>
      </tr>
    </thead>
    <tbody>


      <% @product.specs.each do |spec| %>
        <tr>
          <td><%= spec.id %></td>
          <td><%= spec.bh %></td>
          <td><%= spec.name %></td>
          <td style="background-color: <%= spec.color.value %>">
          </td>
          <td>
            <%= spec.color.name %>
          </td>
          <td>
            <%= spec.material %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div id="spec-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">规格编辑</h3>
    </div>
    <div class="modal-body">

    </div>

  </div>



app/views/products/update.js.erb
# encoding: utf-8
$('#product-modal').modal('hide');
<% flash.now[:notice]="零件信息已成功修改" %>
$('#msg').html("<%=  escape_javascript(notice_message) %> ");
$('#product_<%= @product.id %>').replaceWith("<%= escape_javascript(render(@product)) %>");
$('#product_<%= @product.id %>').fadeOut(1000).fadeIn(1000);